#!/usr/bin/perl -w



use LWP::Simple;
use XML::XPath;
use XML::XPath::Parser;
use RDF::Trine;
use RDF::Trine::Model;
use RDF::Trine::Statement;
use RDF::Trine::Node::Resource;
use RDF::Trine::Node::Literal;
use RDF::Trine::Serializer;


my $url = "http://antirrhinum.net/cgi-bin/ace/generic/xml/DragonDB?name=cho;class=Allele";
my $xml = get($url);


my $xp = XML::XPath->new(xml => $xml);

my $geneid = $xp->getNodeText('/Allele/Source/gene/@value'); # find all paragraphs

my $nodeset = $xp->find('/Allele/Description/Phenotype/@value'); # find all paragraphs
my $desc;
foreach my $node ($nodeset->get_nodelist) {
    $desc .= $node->getData . "\n";
}

my $nodeset = $xp->find('/Allele/Phenotype_picture/@value'); # find all paragraphs
print "=======================\n\n";
print "$geneid   ---   $desc\n\n";
foreach my $node ($nodeset->get_nodelist) {
    print "FOUND  ", $node->getData,       "\n";
}
